### PR TITLE
Fixes for IOS10.

### PR DESCRIPTION
**Pull request by ignaciolarranaga**
Hi guys, some fixes due the last changes of IOS10 I guess.

### CODE REVIEW

**Comment by thomasmoon** [comment]
Thanks for the fixes @ignaciolarranaga ... I'm using the plugin now from your forked repo now and it builds successfully, though having problems with registration.  If this update works it should be integrated into the master asap, cheers!

**Comment by AntonDobrev** [comment]
@ignaciolarranaga @thomasmoon 

Thanks for your input. 

After a short discussion with the contributors and the NativeScript runtime team we decided to incorporate a more robust solution in the plugin.

A few details which might be interesting for you. 

The solution proposed by Ignacio will work only when the app is built against the iOS 10 SDK. It will not work if the app is built against iOS 9 SDK and vice versa. Since the plugin is officially published in the [Telerik Marketplace](http://plugins.telerik.com/nativescript/plugin/telerik-push-notifications) and npm package, we would like to have it compatible with iOS 9 SDK as well. Having said this, we will consider the following approach:

Using the NS _application_ module methods for adding and removing an observer (more info [here] (https://github.com/NativeScript/NativeScript/blob/849736e35e68b3cfcec809c80d251964d805e766/tns-core-modules/application/application.d.ts#L578)) which will ensure the observers are correctly added, independent of the run-time and build-time configurations. 

Let me know should you have further questions or considerations.

**Comment by ignaciolarranaga** [comment]
Thanks !

**Comment by thomasmoon** [comment]
Thanks @AntonDobrev, we have been developing for phones as old as iOS 8, so definitely looking forward to the backwards compatible solution.  Any idea when the Nativescript push-plugin will be updated?

**Pull request closed without merging**
